app.fetch:
  base-url: 'https://m.vk.com'
  search-pattern-age: '/search?c[age_from]=29&c[age_to]=30&c[city]=1&c[country]=1&c[name]=1&c[per_page]=40&c[q]={reservist_name}&c[section]=people'
  search-pattern: '/search?c[bday]=29&c[bmonth]=3&c[city]=1&c[byear]=1992&c[country]=1&c[name]=1&c[per_page]=40&c[q]={reservist_name}&c[section]=people'
  user-pattern: '/{user_id}?act=info'
logging:
  level:
    net.shyshkin: debug
