version: "3.8"
services:
  mockserver:
    build:
      context: .
      dockerfile: Dockerfile-mockserver
      args:
        MOCKSERVER_VERSION: "${MOCKSERVER_VERSION:-latest}"
    ports:
      - "${MOCKSERVER_HOST_PORT:-1080}:1080"
    networks:
      - ${GLOBAL_NETWORK:-services}

