version: "3.8"

name: site-crawler

services:
  fetch-service:
    image: artarkatesoft/art-site-crawler
    ports:
      - '8080:8080'
    environment:
      "logging.level.net.shyshkin": debug
      "logging.level.org.springframework.web.reactive.function.client": debug
      "app.fetch.base-url": 'https://m.vk.com'
      VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN_1}

  vk-rest-api-service:
    image: artarkatesoft/art-vk-rest-api
    ports:
      - '8081:8080'
    environment:
      "logging.level.net.shyshkin": debug
      VK_USER_ID: ${VK_USER_ID}
      VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN_1}
      "app.vk-api.fields": "bdate,city,country,last_seen,deactivated,is_closed,about,activities,books,career,connections,contacts,counters,domain,education,exports,followers_count,has_mobile,has_photo,home_town,military,movies,music,nickname,occupation,quotes,relatives,relation,schools,sex,site,status,universities"