version: "3.8"

name: site-crawler

volumes:
  volume-kibana:
  volume-elastic:

services:
  fetch-service:
    image: artarkatesoft/art-site-crawler
    ports:
      - '8080:8080'
    environment:
      "logging.level.net.shyshkin": debug
      "logging.level.org.springframework.web.reactive.function.client": debug
      "app.fetch.base-url": 'https://m.vk.com'
      VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN_1}

  vk-rest-api-service:
    image: artarkatesoft/art-vk-rest-api
    ports:
      - '8081:8080'
    environment:
      "logging.level.net.shyshkin": debug
      VK_USER_ID: ${VK_USER_ID}
      VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN_1}
      "app.vk-api.fields": "bdate,city,country,last_seen,deactivated,is_closed,about,activities,books,career,connections,contacts,counters,domain,education,exports,followers_count,has_mobile,has_photo,home_town,military,movies,music,nickname,occupation,quotes,relatives,relation,schools,sex,site,status,universities"

  vk-streaming-api-service:
    image: artarkatesoft/art-vk-streaming-api
    ports:
      - '8091:8080'
    environment:
      "logging.level.net.shyshkin": debug
      VK_APP_ID: ${VK_APP_ID}
      VK_APP_ACCESS_TOKEN: ${VK_APP_ACCESS_TOKEN}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-latest}
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - volume-elastic:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-latest}
    ports: ["5601:5601"]
    restart: on-failure
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - volume-kibana:/usr/share/kibana
    depends_on:
      - elasticsearch
