version: "3.8"

name: site-crawler

services:
  fetch-service:
    image: artarkatesoft/art-site-crawler
    ports:
      - '8080:8080'
    environment:
      "logging.level.net.shyshkin": debug
      "app.fetch.base-url": 'https://m.vk.com'
      VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN}
