version: "3.8"

name: site-crawler

services:
  fetch-service:
    image: artarkatesoft/art-site-crawler
    ports:
      - '8080:8080'
    environment:
      "logging.level.net.shyshkin": debug
      "app.site.url-pattern": 'https://m.vk.com/search?c[age_from]=29&c[age_to]=30&c[city]=1&c[country]=1&c[name]=1&c[per_page]=40&c[q]={reservist_name}&c[section]=people'
