server:
  port: 8091

logging:
  level:
    net.shyshkin: debug

app:
  vk-streaming-api:
    app-id: ${VK_APP_ID}
    client-access-token: ${VK_APP_ACCESS_TOKEN}

spring:
  elasticsearch:
    uris: http://elasticsearch:9200
